name: rollback

on: workflow_dispatch

jobs:
  build-version:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |

        git config user.name "Github Bot"
        git config user.email ""
        echo "COMMIT_ID=$(git log -n 1 --pretty=format:"%H")" >> $GITHUB_ENV
        git revert ${{env.COMMIT_ID}}
    
