name: rollback

on: workflow_dispatch

jobs:
  build-version:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |

        git log -n 1 --skip 1 --pretty=format:"%H"
        echo "COMMIT_ID=$(git log -n 1 --skip 1 --pretty=format:"%H")" >> $GITHUB_ENV
        git reset --soft ${{env.COMMIT_ID}}
        git push
    
