name: rollback

on: workflow_dispatch

jobs:
  build-version:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        token: ${{ secrets.PAT_TOKEN }}
     
    - name: git
      run: |
        git config user.name "nylinUA"
        git config user.email "nylin@ualberta.ca"
        COMMIT_ID=$(git log -n 1 --pretty=format:"%H")
        git revert -m 1 "$COMMIT_ID" --no-edit
        git push origin main
    env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
